### ISSUE TITLE
Improve UI/UX for selecting empty cell for delivering order

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#52]
Let's imaging a real work situation. The delivery service has a package to delivery to the parcel locker. They put it into the van and drive to the parcel locker area. They stop at the parcel locker and have to decide which cell to choose. They know the parcel locker number and see the cells numbers as A-1, B-3. But in the Cell Order record they faced with Cell lookup field that required them to enter cell number in C-0XXX format (see screenshot below):
<img width="667" alt="Image" src="https://github.com/user-attachments/assets/3fe58523-62c4-421e-ab9c-79156ada3118" />

It is not user friendly. We need to provide a better user experience. In comments to this ticket put your ideas how can we improve this.

Hints:

- It is better to suggest the smallest empty cell that is big enough for parcel
- Parcel locker could be full. System can inform user about it
- There could be multiple cells that fit to package

**Comment by Roman45321** [comment]
Proposed UI improvements:

1. Instead of having the user manually enter the cell number in the Lookup field for Cell, create an additional Picklist field where positions (A-1, B-2) for only the empty cells that correspond to the selected parcel locker are added via Apex or Flow. The user will select a position, and the corresponding cell will be set in the Lookup field (hidden from the user).
2. Add an interactive scheme of the parcel locker displaying positions with closed and open cells. When a specific cell is clicked, it will automatically be selected in the picklist of positions. If all cells are occupied, a red message (for example) "Parcel locker is fully occupied" will be displayed below.
3. Add a custom button "Select optimal cell," which when clicked, will choose the smallest suitable cell in the picklist based on the size of the parcel. This should also solve the issue if multiple cells are appropriate for the parcel.

Should we implement the proposed improvements?

**Comment by msenyk** [comment]
@Roman45321 There is no need to implement the improvement. But you can try to do it for the sake of learning.

**Comment by Roman45321** [comment]
Implemented:
1. Added a Combo box field where the user can select a cell by its position in the parcel locker and click the "Select cell" button to apply the changes.
2. Added an interactive scheme of the parcel locker that displays the numbers, positions, and statuses of the cells. Clicking on a specific cell will automatically select it in the combo box.
3. Added a "Select optimal cell" button, which, when clicked will automatically select the most optimal (smallest) cell for the given parcel.

If a cell is closed a "lock" icon appears inside it, if it is open, the "lock" icon is not displayed.

Can check it here: https://practicum2024-dev-ed.develop.lightning.force.com/lightning/r/CellOrder__c/a02WV000001jF7JYAU/view

![Image](https://github.com/user-attachments/assets/873308f8-de66-47aa-b26d-df071eaaa4fa)

Added changes to https://github.com/msenyk/sf-practicum-2024/pull/61 pull request.
