### ISSUE TITLE
Know where the cell is located

### ISSUE THREAD

**Issue by msenyk** [msenyk/sf-practicum-2024#9]
We have 48 cells of 7 different types, see #2. But it is not clear where each cell is located inside the Parcel Locker. We need to extend data model to include information about location (placement) of each cell.
This data should help to answer the question: Can you show where this cell is on the schema of the locker?
Make this change as part of repository (pull request)

**Comment by Roman45321** [comment]
I suggest determine the placement of cells in the following way: if we visually divide the parcel locker into 4 columns and 6 rows according to this scheme:

![locker1](https://github.com/user-attachments/assets/67618bf2-12c0-407c-b9c3-12502e03cbae)

And agree that in places where multiple cells fall on one row or column, we use sub-columns and sub-rows. Let's have the numbering of columns and rows start from 0. For example, filled cell might have the position Column: 0 Row: 3 Sub-Column: 1 Sub-Row: 0. This way, an employee (the one who will work with the CRM) will only need to know the main rows and columns in the parcel locker to determine where each cell is.

I've added the necessary fields to the Cell object and made the fields Sub-Column and Sub-Row optional since not all cells will have them. I've created a pull request.
